# ===== STAGE 1: build & publish =====
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# Fichiers globaux (s'ils existent dans ton repo)
COPY nuget.config ./
COPY Directory.Packages.props ./
COPY Directory.Build.props ./
COPY Directory.Build.targets ./
COPY global.json ./

# .csproj (service + refs directes + refs transitives)
COPY src/Identity.API/Identity.API.csproj Identity.API/
COPY src/eShop.ServiceDefaults/eShop.ServiceDefaults.csproj eShop.ServiceDefaults/

# Restore
RUN dotnet restore Identity.API/Identity.API.csproj

# Code (topologie "frère-à-frère" sous /src)
COPY src/Identity.API/ Identity.API/
COPY src/eShop.ServiceDefaults/ eShop.ServiceDefaults/
COPY src/Shared/ Shared/
COPY src/eShop.ServiceDefaults/ eShop.ServiceDefaults/

# Publish
RUN dotnet publish Identity.API/Identity.API.csproj \
    -c Release -o /app/publish /p:UseAppHost=false

# ===== STAGE 2: runtime =====
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENV ASPNETCORE_URLS=http://+:8080
EXPOSE 8080
ENTRYPOINT ["dotnet","Identity.API.dll"]